using System.Drawing.Drawing2D;
namespace MarketplaceHub.UI;

public sealed class MainForm : Form {
 private readonly Panel content = new(){Dock=DockStyle.Fill,BackColor=Color.FromArgb(246,248,252),Padding=new Padding(24)};
 private readonly Label title = new(){AutoSize=true,Font=new Font("Segoe UI",20,FontStyle.Bold),ForeColor=Color.FromArgb(27,35,49)};
 private readonly Label subtitle = new(){AutoSize=true,Font=new Font("Segoe UI",9.5f),ForeColor=Color.FromArgb(104,112,126)};

 public MainForm(){
  Text="Marketplace Hub"; StartPosition=FormStartPosition.CenterScreen; MinimumSize=new Size(1180,760); Size=new Size(1380,860); Font=new Font("Segoe UI",9.5f);
  var shell=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2}; shell.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,238)); shell.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100)); Controls.Add(shell);
  shell.Controls.Add(Sidebar(),0,0);
  var right=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=2}; right.RowStyles.Add(new RowStyle(SizeType.Absolute,88)); right.RowStyles.Add(new RowStyle(SizeType.Percent,100)); right.Controls.Add(Header(),0,0); right.Controls.Add(content,0,1); shell.Controls.Add(right,1,0);
  Dashboard();
 }
 private Control Sidebar(){
  var p=new Panel{Dock=DockStyle.Fill,BackColor=Color.FromArgb(21,28,40),Padding=new Padding(16,20,16,16)};
  p.Controls.Add(new Label{Text="MARKETPLACE\nHUB",AutoSize=true,ForeColor=Color.White,Font=new Font("Segoe UI",15,FontStyle.Bold),Location=new Point(18,20)});
  var m=new FlowLayoutPanel{FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,Location=new Point(12,90),Size=new Size(214,650),Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right}; p.Controls.Add(m);
  Nav(m,"Tổng quan",Dashboard); Nav(m,"Sản phẩm",Products); Nav(m,"Giá sản phẩm",Prices); Nav(m,"Sao chép sản phẩm",Copy); Nav(m,"Đơn hàng FBS",Fbs); Nav(m,"Честный ЗНАК / KIZ",Znak); Nav(m,"Jobs",Jobs); Nav(m,"Lịch sử",History); Nav(m,"Cửa hàng / API",Stores); Nav(m,"Thiết bị",Devices); Nav(m,"Cài đặt",Settings); return p;
 }
 private void Nav(FlowLayoutPanel p,string t,Action a){var b=new Button{Text=t,Width=192,Height=42,FlatStyle=FlatStyle.Flat,TextAlign=ContentAlignment.MiddleLeft,ForeColor=Color.FromArgb(226,231,239),BackColor=Color.FromArgb(21,28,40),Padding=new Padding(12,0,0,0),Margin=new Padding(0,2,0,2)}; b.FlatAppearance.BorderSize=0;b.FlatAppearance.MouseOverBackColor=Color.FromArgb(37,47,64);b.Click+=(_,_)=>a();p.Controls.Add(b);}
 private Control Header(){var p=new Panel{Dock=DockStyle.Fill,BackColor=Color.White};title.Location=new Point(28,15);subtitle.Location=new Point(30,53);p.Controls.Add(title);p.Controls.Add(subtitle);var badge=new Label{Text="DEMO / SCAFFOLD",AutoSize=true,Font=new Font("Segoe UI",9,FontStyle.Bold),ForeColor=Color.FromArgb(28,113,216),BackColor=Color.FromArgb(232,243,255),Padding=new Padding(10,6,10,6),Anchor=AnchorStyles.Top|AnchorStyles.Right};p.Controls.Add(badge);p.Resize+=(_,_)=>badge.Location=new Point(p.ClientSize.Width-badge.Width-24,26);return p;}
 private void Page(string t,string s){title.Text=t;subtitle.Text=s;content.Controls.Clear();}
 private DataGridView Grid(params string[] cs){var g=new DataGridView{Dock=DockStyle.Fill,BackgroundColor=Color.White,BorderStyle=BorderStyle.None,AllowUserToAddRows=false,ReadOnly=true,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,RowHeadersVisible=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect};foreach(var c in cs)g.Columns.Add(Guid.NewGuid().ToString(),c);return g;}
 private void Toolbar(Control body,params string[] bs){var p=new FlowLayoutPanel{Dock=DockStyle.Top,Height=56};foreach(var t in bs){var b=new Button{Text=t,AutoSize=true,Height=36,Padding=new Padding(12,0,12,0),FlatStyle=FlatStyle.Flat,BackColor=Color.White};b.FlatAppearance.BorderColor=Color.FromArgb(210,217,227);p.Controls.Add(b);}content.Controls.Add(body);content.Controls.Add(p);p.BringToFront();}
 private Control Card(string cap,string val,string det){var p=new Panel{Width=250,Height=116,BackColor=Color.White,Margin=new Padding(0,0,14,0)};p.Paint+=(_,e)=>{using var pen=new Pen(Color.FromArgb(226,231,239));e.Graphics.DrawRoundedRectangle(pen,new Rectangle(0,0,p.Width-1,p.Height-1),10);};p.Controls.Add(new Label{Text=cap,AutoSize=true,ForeColor=Color.Gray,Location=new Point(18,15)});p.Controls.Add(new Label{Text=val,AutoSize=true,Font=new Font("Segoe UI",22,FontStyle.Bold),Location=new Point(16,39)});p.Controls.Add(new Label{Text=det,AutoSize=true,ForeColor=Color.FromArgb(73,126,74),Location=new Point(18,87)});return p;}
 private void Dashboard(){Page("Tổng quan","WB • Ozon • Yandex Market • Честный ЗНАК");var f=new FlowLayoutPanel{Dock=DockStyle.Top,Height=145,WrapContents=false};f.Controls.Add(Card("Sản phẩm","1 248","Đã đồng bộ"));f.Controls.Add(Card("Đơn FBS chờ","54","WB 28 • Ozon 17 • YM 9"));f.Controls.Add(Card("KIZ hợp lệ","3 187","63 mã cần kiểm tra"));f.Controls.Add(Card("Job đang chạy","4","Demo data"));content.Controls.Add(f);var l=new Label{Dock=DockStyle.Top,Height=105,Text="Bản 0.1.0 là khung Windows chạy được. API thật chưa kích hoạt để tránh ghi nhầm tài khoản seller. Xem PROMPT.md để triển khai production adapters, SQLite/DPAPI, True API và packing workflow.",Font=new Font("Segoe UI",11),Padding=new Padding(8,18,8,8)};content.Controls.Add(l);l.BringToFront();}
 private void Products(){Page("Sản phẩm","Catalog chuẩn hóa dùng chung cho ba marketplace");var g=Grid("Marketplace","Shop","SKU","Tên","Giá","Trạng thái");g.Rows.Add("WB","WB Shop 01","BLACK-XL","Quần nam đen XL","3 200 ₽","OK");g.Rows.Add("Ozon","Ozon Store 01","BLACK-XL","Брюки мужские","3 550 ₽","OK");g.Rows.Add("Yandex","YM Store 01","BLACK-XL","Брюки мужские","3 680 ₽","OK");Toolbar(g,"Đồng bộ","Tìm SKU","Xuất Excel");}
 private void Prices(){Page("Giá sản phẩm","Preview • batch • verify • rollback");var g=Grid("Chọn","Sàn","SKU","Giá hiện tại","Giá mới","%","Trạng thái");g.Rows.Add("✓","WB","BLACK-XL","3 200 ₽","3 520 ₽","+10%","Sẵn sàng");g.Rows.Add("✓","Ozon","BLACK-2XL","3 300 ₽","3 630 ₽","+10%","Sẵn sàng");Toolbar(g,"Tăng %","Giảm %","Giá cố định","Import Excel","Xem trước","Cập nhật giá");}
 private void Copy(){Page("Sao chép sản phẩm","Source → normalized catalog → mapper → destination");var g=Grid("Nguồn","SKU","Đích","Category","Attributes","Ảnh","Kết quả");g.Rows.Add("WB Shop 01","BLACK-XL","Ozon Store 02","Matched","18/20","7","Thiếu 2 thuộc tính");g.Rows.Add("Ozon Store 01","NAVY-XL","Yandex Store 01","Matched","20/20","6","Sẵn sàng");Toolbar(g,"Chọn nguồn","Chọn đích","Phân tích tương thích","Sao chép hàng loạt");}
 private void Fbs(){Page("Đơn hàng FBS","Packing Station: scan → KIZ → pack → label → shipment");var g=Grid("Ưu tiên","Sàn","Đơn","SKU","SL","KIZ","Nhãn","Trạng thái");g.Rows.Add("P1","Ozon","0139282-0034-1","BLACK-XL","1/1","Required","Chưa in","Chờ đóng");g.Rows.Add("P2","WB","18473920193","NAVY-2XL","1/1","OK","Ready","Đang đóng");g.Rows.Add("P4","Yandex","YM-920183","BLACK-3XL","2/2","N/A","Ready","Sẵn sàng giao");Toolbar(g,"Quét barcode / DataMatrix","Nhận đơn","Xác nhận đóng","In nhãn","Tạo / giao lô");}
 private void Znak(){Page("Честный ЗНАК / KIZ","True API + УКЭП qua CryptoPro/Rutoken; không lưu private key/PIN");var g=Grid("KIZ","GTIN","Status","Crypto","Owner","Blocked","Kết quả");g.Rows.Add("010460...21ABC","04607144353175","INTRODUCED","✓","✓","Không","Hợp lệ");g.Rows.Add("010460...21XYZ","04607144353175","RETIRED","✓","✓","Không","Không dùng");Toolbar(g,"Kiểm tra kết nối","Chọn УКЭП","Quét KIZ","Kiểm tra hàng loạt","Kho KIZ","Tài liệu");}
 private void Jobs(){Page("Jobs","Persisted state machine cho mọi batch/write");var g=Grid("Job","Loại","Sàn","Tiến độ","Trạng thái","Chi tiết");g.Rows.Add("#1042","PRICE_UPDATE","WB","483/500","VERIFYING","17 item đang chờ");g.Rows.Add("#1043","COPY_PRODUCT","Ozon","31/37","PARTIAL_SUCCESS","6 item cần retry");Toolbar(g,"Retry lỗi","Tạm dừng","Tiếp tục","Xuất log");}
 private void History(){Page("Lịch sử","Audit giá, copy, KIZ, packing, chữ ký và shipment");var g=Grid("Thời gian","Module","Đối tượng","Thao tác","Kết quả");g.Rows.Add(DateTime.Now.AddMinutes(-15).ToString("g"),"Giá","WB / BLACK-XL","3200 → 3520","OK");g.Rows.Add(DateTime.Now.AddMinutes(-9).ToString("g"),"FBS","WB order 18473920193","Sticker printed","OK");Toolbar(g,"Lọc","Xuất CSV","Rollback giá");}
 private void Stores(){Page("Cửa hàng / API","Multi-store; production secrets phải DPAPI");var g=Grid("Marketplace","Tên","ID","Quyền","Kết nối");g.Rows.Add("Wildberries","WB Shop 01","—","Content + Prices + FBS","Demo");g.Rows.Add("Ozon","Ozon Store 01","Client ID","Seller API","Demo");g.Rows.Add("Yandex","YM Store 01","Business/Campaign","Partner API","Demo");Toolbar(g,"Thêm WB","Thêm Ozon","Thêm Yandex","Kiểm tra API");}
 private void Devices(){Page("Thiết bị","Scanner, printer 58×40/ZPL/PDF và cân");var g=Grid("Thiết bị","Tên","Profile","Trạng thái");g.Rows.Add("Scanner","USB HID Scanner","Auto detect","Demo");g.Rows.Add("Printer","XPrinter 58×40","Label default","Demo");g.Rows.Add("Scale","COM device","Optional","Chưa cấu hình");Toolbar(g,"Quét thiết bị","In thử","Lưu station");}
 private void Settings(){Page("Cài đặt","Theme, auto-sign, sync, job limits, API environment");var l=new Label{Dock=DockStyle.Fill,BackColor=Color.White,Padding=new Padding(24),Font=new Font("Segoe UI",11),Text="Production checklist:\n\n• SQLite + migrations\n• DPAPI secrets\n• WB/Ozon/Yandex adapters\n• True API challenge signing qua CryptoPro\n• Auto-sign whitelist, không lưu PIN/private key\n• Idempotency + verify-after-write\n• Rate limiter riêng từng marketplace\n• Printer/ZPL/PDF pipeline\n• Structured audit log + rollback"};content.Controls.Add(l);}
}
internal static class GraphicsExtensions {
 public static void DrawRoundedRectangle(this Graphics g,Pen p,Rectangle b,int r){int d=r*2;using var path=new GraphicsPath();path.AddArc(b.X,b.Y,d,d,180,90);path.AddArc(b.Right-d,b.Y,d,d,270,90);path.AddArc(b.Right-d,b.Bottom-d,d,d,0,90);path.AddArc(b.X,b.Bottom-d,d,d,90,90);path.CloseFigure();g.DrawPath(p,path);}
}